# Generated by Django 3.0.8 on 2020-08-11 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbooks',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
